### ISSUE TITLE
Control grpc connect will panic

### ISSUE THREAD

**Issue by frostRed** [vorot93/ethereum-sentry#1]
It will panic if I provide the Control address in the config file. It will trigger even I don't run a real Control to listen to the address.

```
thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime'
```
It seems caused by `src/services/control.rs L26`.

**Comment by frostRed** [comment]
Btw, I fixed the master branch compile error by adding this in the `Cargo.toml`

```
[patch."https://github.com/sigp/discv5"]
discv5 = { git = "https://github.com/vorot93/discv5", branch = "bytes" }
```

**Comment by vorot93** [comment]
Should be fixed now.
